export { default as figma } from "../assets/icones/figma.svg";
export { default as html } from "../assets/icones/html.svg";
export { default as css } from "../assets/icones/css.svg";
export { default as react } from "../assets/icones/react.svg";
export { default as javaScript } from "../assets/icones/javascript.svg";
export { default as git } from "../assets/icones/git.svg";
export { default as imgbanner } from "../assets/images/image_banner.png";
export { default as setright } from "../assets/icones/setas/setright.png";
export { default as setleft } from "../assets/icones/setas/setleft.png";
